// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLLYFcv7mM0lzUu7jYb0fipbpgODBcbF4',
    appId: '1:675384060595:web:1a4ee0fcce9194e1ccdec6',
    messagingSenderId: '675384060595',
    projectId: 'dacn-8a822',
    authDomain: 'dacn-8a822.firebaseapp.com',
    databaseURL: 'https://dacn-8a822-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dacn-8a822.firebasestorage.app',
    measurementId: 'G-PZWBTLBSQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGkU6Qe7sqkNeFyRNzrLSZ6mbdvCoiYDA',
    appId: '1:675384060595:android:16d1aae73ba57bf5ccdec6',
    messagingSenderId: '675384060595',
    projectId: 'dacn-8a822',
    databaseURL: 'https://dacn-8a822-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dacn-8a822.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbP_-PsgK65ttwsyrJhHyt6NFKNkArHJg',
    appId: '1:675384060595:ios:341d0a1fd480dfdbccdec6',
    messagingSenderId: '675384060595',
    projectId: 'dacn-8a822',
    databaseURL: 'https://dacn-8a822-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dacn-8a822.firebasestorage.app',
    androidClientId: '675384060595-83to86a45v22pc9k4r25jqhus9n9ud50.apps.googleusercontent.com',
    iosClientId: '675384060595-8uogd724o7cgm5hkf6us0jpsml627kql.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbP_-PsgK65ttwsyrJhHyt6NFKNkArHJg',
    appId: '1:675384060595:ios:2d3b154081555fd9ccdec6',
    messagingSenderId: '675384060595',
    projectId: 'dacn-8a822',
    databaseURL: 'https://dacn-8a822-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dacn-8a822.firebasestorage.app',
    androidClientId: '675384060595-83to86a45v22pc9k4r25jqhus9n9ud50.apps.googleusercontent.com',
    iosClientId: '675384060595-jh4c1bl7rsb2qbt4jq55curpf3neb5hv.apps.googleusercontent.com',
    iosBundleId: 'x',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLLYFcv7mM0lzUu7jYb0fipbpgODBcbF4',
    appId: '1:675384060595:web:fde286b2e41f63bcccdec6',
    messagingSenderId: '675384060595',
    projectId: 'dacn-8a822',
    authDomain: 'dacn-8a822.firebaseapp.com',
    databaseURL: 'https://dacn-8a822-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dacn-8a822.firebasestorage.app',
    measurementId: 'G-TNL8JH1M1W',
  );

}